// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttrPanel: typeof import('./src/components/common/AttrPanel.vue')['default']
    BarChart: typeof import('./src/components/echart/BarChart.vue')['default']
    LineChart: typeof import('./src/components/echart/LineChart.vue')['default']
    PieChart: typeof import('./src/components/echart/PieChart.vue')['default']
    SideBar: typeof import('./src/components/common/SideBar.vue')['default']
    TableWidget: typeof import('./src/components/echart/TableWidget.vue')['default']
    ToolBar: typeof import('./src/components/common/ToolBar.vue')['default']
    Widget_preview: typeof import('./src/components/echart/widget_preview.vue')['default']
  }
}
